apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress-api
  template:
    metadata:
      labels:
        app: progress-api
    spec:
      containers:
      - name: progress-api
        image: progress-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8003
        env:
        - name: PORT
          value: "8003"
---
apiVersion: v1
kind: Service
metadata:
  name: progress-api
spec:
  type: NodePort
  selector:
    app: progress-api
  ports:
  - port: 8003
    targetPort: 8003
    nodePort: 30003
