apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-runner
  template:
    metadata:
      labels:
        app: code-runner
    spec:
      containers:
      - name: code-runner
        image: code-runner:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          value: "8002"
---
apiVersion: v1
kind: Service
metadata:
  name: code-runner
spec:
  type: NodePort
  selector:
    app: code-runner
  ports:
  - port: 8002
    targetPort: 8002
    nodePort: 30002
