apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-runner
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-runner
  template:
    metadata:
      labels:
        app: code-runner
    spec:
      containers:
      - name: code-runner
        image: code-runner:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        env:
        - name: OPENAI_API_KEY
          value: "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"
---
apiVersion: v1
kind: Service
metadata:
  name: code-runner
  namespace: default
spec:
  type: NodePort
  selector:
    app: code-runner
  ports:
  - port: 8002
    targetPort: 8002
    nodePort: 30002